services:
  retina-scan-postgres-homolog:
    image: postgres:15-alpine
    container_name: retina-scan-postgres-homolog
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retina-scan
    env_file:
      - env/.env.prod
    volumes:
      - postgres_data_homolog:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - retina-scan-network
    restart: unless-stopped

  retina-scan-api-homolog:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: retina-scan-api-homolog
    env_file:
      - env/.env.prod
    depends_on:
      retina-scan-postgres-homolog:
        condition: service_healthy
    networks:
      - retina-scan-network
      - web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.retina-api.rule=Host(`homologapi.retinascan.site`)"
      - "traefik.http.routers.retina-api.entrypoints=websecure"
      - "traefik.http.routers.retina-api.tls=true"
      - "traefik.http.routers.retina-api.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.retina-api.service=retina-api-svc"
      - "traefik.http.services.retina-api-svc.loadbalancer.server.port=3000"

  redis:
    image: redis:7.2.4
    container_name: retina-scan-redis-homolog
    env_file:
      - ./env/.env.prod
    volumes:
      - redis_data:/data
    networks:
      - retina-scan-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    command: redis-server --requirepass redispw
    restart: always

volumes:
  postgres_data_homolog:
  redis_data:

networks:
  retina-scan-network:
    driver: bridge
    name: retina-scan-prod-net

  web:
    external: true
    name: web